name: "Retreive SF Org"
on:
    push:
        branches:
            [ develop, master ]
        paths:
            - 'force-app/**'
    workflow_dispatch:
jobs:
    install-sf-cli:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v4
            - name: Installing sf cli
              run: |
                echo Installing sf...
                curl https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64.tar.gz -o ./sf-win32-x64.tar.gz
                mkdir -p sf-cli
                ls -la
                tar -xzf sf-linux-x64.tar.gz -C sf-cli --strip-components 1
                echo "${PWD}/sf-cli/bin" >> $GITHUB_PATH
            - name: Checking sf cli
              run: sf --version
            - name: Write Auth URL to File
              run: echo "${{ secrets.SF_TRG_SECURITY }}" > dxsecurity
            - name: Authorize Org via Auth URL
              run: |
                sf org login sfdx-url --sfdx-url-file dxsecurity --alias ${{ secrets.SF_TRG_ORG_ALIAS }} --set-default
                echo "Authorized org and set alias to [${{ secrets.SF_TRG_ORG_ALIAS }}]"

                