name: "Retreive SF Org"
on:
    push:
        branches:
            [ develop, master ]
        paths:
            - 'force-app/**'

        # only one can be used paths or paths-ignore, both can't be used at a time
        # paths-ignore:
        #     - '.github/workflows/**'

    workflow_dispatch:
jobs:
    validate-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v3
              with:
                ref: ${{ github.event.inputs.source_branch }}

            - name: Debug:Show directory structure
              run: |
                echo "Current directory: $(pwd)"
                ls -la
                ls -la force-app || echo "force-app does not exist"

            - name: Installing sf cli
              run: |
                echo Installing sf...
                curl https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.gz -o sf-linux-x64.tar.gz
                mkdir -p sf-cli
                tar -xzf sf-linux-x64.tar.gz -C sf-cli --strip-components 1
                echo "${PWD}/sf-cli/bin" >> $GITHUB_PATH

            - name: Checking sf cli
              run: sf --version

            - name: Write Auth URL to File
              run: echo "${{ secrets.SF_TRG_SECURITY }}" > dxsecurity

            - name: Authorize Org via Auth URL
              run: |
                sf org login sfdx-url --sfdx-url-file dxsecurity --alias ${{ secrets.SF_TRG_ORG_ALIAS }} --set-default
                echo "Authorized org and set alias to [${{ secrets.SF_TRG_ORG_ALIAS }}]"

            - name: Show Org Details
              run: sf org display --target-org ${{ secrets.SF_TRG_ORG_ALIAS }} --verbose

            - name: Get Metadata List from Org
              run: |
                sf org list metadata-types --target-org ${{ secrets.SF_TRG_ORG_ALIAS }} --apiversion 64.0 --json \
                | jq -r '.result.metadataObjects[].xmlName' | sort -u > supported-types.txt